create Database customer_behaviour;
use customer_behaviour;
select Top 10 * 
from customer 

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer 
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased, round(avg(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc



-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select * from customer limit 5;
select shipping_type,
AVG(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select * from customer limit 5;

select subscription_status,
COUNT(customer_id) as Total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
FROM customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
order by discount_rate desc;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
USE customer_behaviour;
select top 5 * from customer;

WITH customer_type as 
(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
FROM customer		
)
SELECT customer_segment,COUNT(*) as 'Number of Customers'
FROM customer_type
group by customer_segment
order by 'Number of Customers' desc


-- Q8. What are the top 3 most purchased products within each category?
WITH ProductRank AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS Total_Orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
    category,
    item_purchased,
    Total_Orders,
    item_rank
FROM ProductRank
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status
-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;